export interface MovieRequest {
    id:number;
    title:string;
    overview:string;
    tagline:string;
    budget:number;
    revenue:number;
    imdbUrl:string;
    tmdbUrl:string;
    posterUrl:string;
    backdropUrl:string;
    originalLanguage:string;
    releaseDate:Date;
    runTime:number;
    price:number;
    createdDate:Date;
    updatedDate:Date;
    createdBy:string;
    updatedBy:string;
}
